config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: {
    confirmations: 'confirmations'
  }
  get 'welcome/index'

  resources :products do
    member do
      patch :update_bid
    end
  end

  resources :categories

  get '/profiles/rank' => 'profiles#rank'
  get 'profiles/rank_request' => 'profiles#rank_request'
  resources :profiles

  root 'welcome#index'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  include ProfilesHelper

  belongs_to :user
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, 
                      default_url: "/images/:style/avatar.jpg",
                      dependent: :destroy

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :name, persence: false, length: { in: 3..20 }, format: { with: /\A[a-zA-Z ]+\z/, message: "only allows letters" }, on: :update

end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[edit show update destroy rank_request destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def index
    if params[:val].present?
      @users = User.includes(:profile).where(role: params[:val])
      @role = @users.first.role unless @users.empty?
    else
      @users = User.includes(:profile).all
      @role = "user"
    end
  end

  def show
    @author = @profile.user
    @products_sold = @author.products.where(status: "sold").size
    @products_bought = Bid.where(status: "sold").where(buyer_id: @author.id).size
    render :show
  end

  def update
    @author = @profile.user
    @profile.update(image: image_params) if params[:profile][:image]
    if @profile.update(profile_params)
      redirect_to @profile, notice: "Profile Updated Successfully"
    else
      render :show
    end
  end

  def rank
    user = User.find_by_id(params[:id])
    if user.user?
      user.moderator!
    elsif user.moderator?
      user.user!
    end
    redirect_to(:back)
  end

  def rank_request
    user = User.find_by_id(params[:user_id])
    if user.update(moderator_request: true)
      respond_to do |format|
        format.html { redirect_to @profile, notice: "Your Request Sent Successfully" }
        format.js
      end
    end
  end

  def destroy; end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:name, :location, :country, :bio, :mobile, :image)
  end

  def image_params
    params[:profile][:image]
  end

  def record_not_found
    # render partial: 'layouts/not_found', status: 404
  end

  def user_paginate
    @users = @users.paginate(page: params[:page], per_page: 20)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper

end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="col-md-11">
	<div class="article-title-font">Edit Profile</div>

	<%= form_for profile = @profile do |f| %>
		<!-- <div>
			<% if profile.errors.any? %>
		    	<div id="error_explanation" class="alert">
		      		<h2><%= pluralize(profile.errors.count, "error") %> Prohibited this Profile from being saved:</h2>

		      		<ul>
		        		<% profile.errors.full_messages.each do |msg| %>
		          			<li><%= msg %></li>
		          		<% end %>
		      		</ul>
		    	</div>
		  	<% end %>		
		</div>
	 -->

		<div class="form-group">
			<%= f.label :profile_picture, class: 'label' %><br>
			<% unless profile.image.nil? %>
			<%= image_tag "/profiles/images/#{profile.image.name}", height: '180', width: '200' %>
			<% end %>
			<%= f.file_field :image, required: false, autofocus: true, class: 'form-control fa fa-pencil-square-o text-info icon-size', style: 'width: 8%; border:none; vertical-align: bottom',  title: 'Choose Picture'%>
			<p class='error'><%= show_errors(profile , :image) %></p>
		</div>
		<div class="form-inputs">
			<div class="form-group">
				<%= f.label :name, class: 'label' %>
				<%= f.text_field :name, required: false, autofocus: true, class: 'form-control' %>
				<p class='error'><%= show_errors(profile , :name) %></p>
			</div>

			<div class="form-group">
				<%= f.label :public_email, class: 'label' %>
				<%= f.text_field :public_email, required: false,
				hint: "leave it blank if you don't want to add it",
				class: 'form-control' %>
				<p class='error'><%= show_errors(profile , :public_email) %></p>
			</div>

			<div class="form-group">
				<%= f.label :location, class: 'label' %>
				<%= f.text_field :location,
				hint: "leave it blank if you don't want to add it",
				required: false,
				class: 'form-control' %>
				<p class='error'><%= show_errors(profile , :location) %></p>
			</div>

			<div class="form-group">
				<%= f.label :country, class: 'label' %>
				<%= f.text_field :country,
				hint: "leave it blank if you don't want to add it",
				required: false,
				class: 'form-control' %>
				<p class='error'><%= show_errors(profile , :country) %></p>
			</div> 

			<div class="form-group">
				<%= f.label :profession, class: 'label' %>
				<%= f.text_field :profession,
				hint: "leave it blank if you don't want to add it",
				required: false,
				class: 'form-control' %> 
				<p class='error'><%= show_errors(profile , :profession) %></p>
			</div>

			<div class="form-group">
				<%= f.label :organization, class: 'label' %>
				<%= f.text_field :organization,
				hint: "leave it blank if you don't want to add it",
				required: false,
				class: 'form-control' %> 
				<p class='error'><%= show_errors(profile , :organization) %></p> 
			</div>


			<div class="form-group">
				<%= f.label :social_media_links, class: 'label' %>
				
				<div class="form-group row">
					<div class="col-md-2"><%= f.label :facebook, class: 'label' %></div>
					<div class="col-md-9"><%= f.text_field :facebook,
					hint: "leave it blank if you don't want to add it",
					required: false,
					class: 'form-control' %> </div>
					<p class='error'><%= show_errors(profile , :facebook) %></p> 
				</div>

				<div class="form-group row">
					<div class="col-md-2"><%= f.label :twitter, class: 'label' %></div>
					<div class="col-md-9"><%= f.text_field :twitter,
					hint: "leave it blank if you don't want to add it",
					required: false,
					class: 'form-control' %> </div>
					<p class='error'><%= show_errors(profile , :twitter) %></p> 
				</div>

				<div class="form-group row">
					<div class="col-md-2"><%= f.label :instagram, class: 'label' %></div>
					<div class="col-md-9"><%= f.text_field :instagram,
					hint: "leave it blank if you don't want to add it",
					required: false,
					class: 'form-control' %> </div>
					<p class='error'><%= show_errors(profile , :instagram) %></p> 
				</div>

				<div class="form-group row">
					<div class="col-md-2"><%= f.label :linkedin, class: 'label' %></div>
					<div class="col-md-9"><%= f.text_field :linkedin,
					hint: "leave it blank if you don't want to add it",
					required: false,
					class: 'form-control' %> </div>
					<p class='error'><%= show_errors(profile , :linkedin) %></p> 
				</div>

				<div class="form-group row">
					<div class="col-md-2"><%= f.label :youtube, class: 'label' %></div>
					<div class="col-md-9"><%= f.text_field :youtube,
					hint: "leave it blank if you don't want to add it",
					required: false,
					class: 'form-control' %> </div>
					<p class='error'><%= show_errors(profile , :youtube) %></p> 
				</div>
			</div>

			<div class="form-group">
				<%= f.label :write_about_yourself, class: 'label' %>
				<%= f.cktext_area :bio,
				hint: "leave it blank if you don't want to add it",
				required: false,
				class: 'form-control' %> 
				<p class='error'><%= show_errors(profile , :bio) %></p> 
			</div>
		</div>

		<div class="form-group">
			<%= f.submit "Submit", class: 'btn btn-success ' %>
		</div>

	<% end %>

	<div>Unhappy? <%= link_to "Delete my account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete %></div>
	<div>
		<%= link_to 'Change Password', edit_registration_path(current_user) %> |
		<%= link_to "Back", :back %> 
	</div>

</div>

app/views/profiles/index.html.erb
<% if signed_in? && current_user.admin? %>
  <div class="col-md-12">
    <div class="">
      <div class="btn-group mt-2" style='margin-left: 78rem;'>
        <button class="btn btn-info btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Filter
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to 'All', profiles_path, class: 'dropdown-item' %>
          <%= link_to 'Moderators', profiles_path(:val => 1), class: 'dropdown-item' %>
          <%= link_to 'Users', profiles_path(:val => 2), class: 'dropdown-item' %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <% if @users.empty? %>
      <div>
        <h2 class="text-danger text-center">No Users Found</h2>
      </div>
    <% else %>
      <section id="team" class="pb-5">
        <div class="container">
          <h5 class="section-title h1">
            <% if @role.nil? %>
              Users
            <% else %>
              <%= @role.pluralize.humanize %>
            <% end %> List</h5>
          <div class="row">
            <% @users.each do |user|%>
              <!-- Team member -->
              <div class="col-xs-12 col-sm-6 col-md-4">
                <%# <div class="image-flip" ontouchstart="this.classList.toggle('hover');"> %>
                <div class="">
                  <div class="mainflip">
                    <div class="frontside">
                      <div class="card">
                        <div class="card-body text-center">
                          <p>
                            <% if user.profile.image.present?%>
                              <%= image_tag user.profile.image.url, class: "author-img" %>
                            <% else %>
                              <%= image_tag(image_path('avatar.jpg'), class: "author-img") %>
                            <% end %>
                          </p>
                          <h4 class="card-title">
                            <%= link_to  get_user_name(user.profile).humanize, profile_path(user.profile.id), target: 'blank', class: "standard-link text-info" %>
                            (<%= user.role.humanize %>)
                          </h4>
                          <p class="card-text">
                            <% if user.profile.bio.present? %>
                              <%= user.profile.bio %>
                            <% else %>
                              This section shows the user bio. Currently no bio added by the user
                            <% end %>
                          </p>
                          <% if user.user? %>
                            <div class="">
                              <%= link_to 'Promote', profiles_rank_path(:id => user.id), class: 'text-success col-md-2', title: 'Make Moderator' %>
                            </div>
                          <% elsif user.moderator? %>
                            <div class="">
                              <%= link_to 'Demote', profiles_rank_path(:id => user.id), class: 'text-danger col-md-2', title: 'Make User' %>
                            </div>
                          <% end %>
                        </div>
                      </div>
                    </div>
                    <div class="backside">
                      <div class="card">
                        <div class="card-body text-center mt-4">
                          <h4 class="card-title">User Bio Section</h4>
                          <p class="card-text">
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </section>
    <% end %>
  </div>
<% else %>
  You Are not authorized to visit this page <br>
  <%= link_to 'Go to Homepage', root_path, class: 'btn btn-info' %>
<% end %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/rank_request.js.erb
$(document).ready(function(){
	$("#rank-request-link").fadeOut(function(){
		$(this).fadeIn().html("<span class='text-success'>Your request has been sent successfully</span>");	
	});
});

app/views/profiles/show.html.erb
<div class="container" style="margin-top: 15rem;">
  <% if @profile %>
    <% user = @profile.user %>
    <div class="col-md-12">
      <div class="card border-info mx-sm-1 p-3" style="width: 100%; margin-top: 10rem;">
        <div class="card border-info shadow text-info p-3 profile-image">
          <% if @profile.image.present? %>
            <%= image_tag @profile.image.url, class: 'profile-picture' %>
          <% else %>
            <%= image_tag(image_path('avatar.jpg'), style: 'width: 100%') %>
          <% end %>
          <% if signed_in? && (current_user == @author || @profile == current_user.profile) %>
            <button type="button" class="icon2" data-toggle="modal" data-target="#profile-image">
              <i class="fa fa-pencil-square-o"></i>
            </button>
          <% end %>
          <div class="text-info text-center text-uppercase w-100">
            <h4><%= @profile.name || @profile.user.email.split('@').first.humanize %></h4>
          </div>
        </div>
        <div class="row vertical-divider ">
          <div class="col-md-6 ">
            <p class="h4 text-info">Activities</p>
            <hr>
            <div class="row ml-5 text-left">
              <dt class="col-md-5">Products Entered:</dt>
              <dd class="col-md-7"><%=@author.products.size%></dd>
            </div>
            <div class="row ml-5 text-left">
              <dt class="col-md-5">Products Sold:</dt>
              <dd class="col-md-7"><%=@products_sold%></dd>
            </div>
            <div class="row ml-5 text-left">
              <dt class="col-md-5">Products Bought:</dt>
              <dd class="col-md-7"><%=@products_bought%></dd>
            </div>
          </div>
          <div class="col-md-6">
            <p class="h4 text-info">
              Details
              <button type="button" data-toggle="modal" data-target="#profile">
                <i class="fa fa-pencil-square-o"></i>
              </button>
            </p>
            <hr>
            <div class="row ml-5 text-left">
              <dt class="col-md-3">Name:</dt>
              <dd class="col-md-9 text-left"><%=get_user_name(@author.profile)%></dd>
            </div>
            <div class="row ml-5 text-left">
              <dt class="col-md-3">Email:</dt>
              <dd class="col-md-9 text-left"><%=@author.email%></dd>
            </div>
            <div class="row ml-5 text-left">
              <dt class="col-md-3">Country:</dt>
              <dd class="col-md-9 text-left"><%=@profile.country || "N/A"%></dd>
            </div>
            <div class="row ml-5 text-left">
              <dt class="col-md-3">Location:</dt>
              <dd class="col-md-9 text-left"><%=@profile.location || "N/A"%></dd>
            </div>
            <div class="row ml-5 text-left">
              <dt class="col-md-3">Mobile:</dt>
              <dd class="col-md-9 text-left"><%=@profile.mobile || "N/A"%></dd>
            </div>
          </div>
        </div>
        <hr>
        <div class="ml-auto">
          <% if user == current_user %>
            <%= link_to 'Change Password', edit_user_registration_path, class: 'user-content text-info float-right' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% else %>
  <%= link_to 'Go to Dashboard', profile_path(current_user.profile), class: 'btn btn-info'  %>
<% end %>
</div>
<!-- Bio Edit -->
<div class="modal fade" id="bio">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Edit Bio</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <%= form_for @profile, html: { id: :bio_form } do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :write_about_yourself, class: 'label' %>
            <%= f.cktext_area :bio,
            hint: "leave it blank if you don't want to add it",
            required: false,
            class: 'form-control' %>
            <p class='error' id="bio-error"><%= show_errors(@profile , :bio) %></p>
          </div>
        </div>
        <div class="modal-footer text-center">
          <%= f.button 'Update Bio', type: :button, class: 'btn btn-success', id: "bio-validate" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!-- Profile Edit -->
<div class="modal fade" id="profile">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Edit Profile</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <%= form_for @profile, html: { id: :profile_details_form } do |f| %>
        <div class="modal-body">
          <div class="form-inputs">
            <div class="form-group row">
              <div class="col-md-4"><%= f.label :name, class: 'label' %><span class="text-danger">*</span></div>
              <div class="col-md-8" id="name-div">
                <%= f.text_field :name, required: false, autofocus: true, class: 'form-control', validate: { presence: true } %>
                <p class='error' id="name-error"><%= show_errors(@profile , :name) %></p>
              </div>
            </div>
            <div class="form-group row">
              <div class="col-md-4"><%= f.label :mobile, class: 'label' %><span class="text-danger">*</span></div>
              <div class="col-md-8" id="mobile-div">
                <%= f.text_field :mobile, required: false, class: 'form-control' %>
                <p class='error' id="mobile-error"><%= show_errors(@profile , :mobile) %></p>
              </div>
            </div>
            <div class="form-group row">
              <div class="col-md-4">
                <%= f.label :location, class: 'label' %></div>
              <div class="col-md-8">
                <%= f.text_field :location,
                    hint: "leave it blank if you don't want to add it",
                    required: false, class: 'form-control' %>
                <p class='error'><%= show_errors(@profile , :location) %></p>
              </div>
            </div>
            <div class="form-group row">
              <div class="col-md-4">
                <%= f.label :country, class: 'label' %></div>
              <div class="col-md-8">
                <%= f.text_field :country,
                    hint: "leave it blank if you don't want to add it",
                    required: false, class: 'form-control' %>
                <p class='error'><%= show_errors(@profile , :country) %></p>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :write_about_yourself, class: 'label' %>
              <%= f.cktext_area :bio,
                  hint: "leave it blank if you don't want to add it",
                  required: false,
                  class: 'form-control' %>
              <p class='error' id="bio-error"><%= show_errors(@profile , :bio) %></p>
            </div>
          </div>
          <div class="modal-footer text-center">
            <%= f.button 'Update Profile Details', type: :button, class: 'btn btn-success', id: "profile-validate" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
<!-- End -->
<!-- Profile Pic Edit -->
<div class="modal fade" id="profile-image">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Edit Profile Picture</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <%= form_for @profile, html: { id: :image_form } do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :profile_picture, class: 'label' %><br>
            <% if @profile.image.present? %>
              <%= image_tag @profile.image.url, class: 'profile-image', style: 'width: auto;' %>
            <% else %>
              <%= image_tag(image_path('avatar.jpg'), height: '180', width: '200') %>
            <% end %>
            <%= f.hidden_field :id %>
            <%= f.file_field :image, required: true, autofocus: true, class: 'form-control ',  title: 'Choose Picture' %>
            <p class='error' id="image-error"><%= show_errors(@profile , :image) %></p>
          </div>
        </div>
        <div class="modal-footer text-center">
          <%= f.button 'Update Profile Picture', type: :button, class: 'btn btn-success', id: "image-validate" %>
        </div>
      <% end %>
    </div>
  </div>
</div>