config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: {
    confirmations: 'confirmations'
  }
  get 'welcome/index'

  resources :products do
    member do
      patch :update_bid
    end
  end

  resources :categories

  get '/profiles/rank' => 'profiles#rank'
  get 'profiles/rank_request' => 'profiles#rank_request'
  resources :profiles

  root 'welcome#index'
end

app/models/product.rb
# frozen_string_literal: true

class Product < ActiveRecord::Base
  include ProfilesHelper
  
  belongs_to :user
  belongs_to :category
  has_one :bid, dependent: :destroy

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, 
                      default_url: "/images/:style/box.png",
                      dependent: :destroy
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  after_create :set_default, :create_bid

  private

  def set_default
    update_attributes(status: 'pending')
  end

  def create_bid
    self.bid = Bid.create(current_bid: price, status: 'pending', product: self)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy update_bid]
  before_action :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @bid_user = if @product.bid.buyer_id
        User.find(@product.bid.buyer_id)
      else
        current_user
      end
    @bid_user_name = get_user_name(@bid_user)
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def update_bid
    respond_to do |format|
      if valid_bid
        if @product.bid.update(product_bid_params)
          format.html { redirect_to @product, notice: "Bid Placed Successfully." }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { redirect_to @product }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to @product, notice: { type: "error", message: "Bid Price Must Be Higher Than Previous Bid Price." } }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:category_id, :name, :price, :image, :description, :last_bidding_date)
  end

  def product_bid_params
    user_name = get_user_name(current_user)
    params.require(:bid).permit(:current_bid).merge!({ buyer_id: current_user.id, buyer_name: user_name })
  end

  def get_user_name(user)
    user.profile.name || user.email.split("@").first
  end

  def valid_bid
    @product.bid.current_bid.to_f < params[:bid][:current_bid].to_f
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container w-50">
  <%= form_for @product, html: { multipart: true } do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
        <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group row">
      <label for="productCategory" class="col-sm-2 col-form-label">Product Category</label>
      <div class="col-sm-10 category-select">
        <%= f.collection_select :category_id, Category.order(:name),:id,:name, {prompt: "Select a category"}, required: true %>
      </div>
    </div>
    <div class="form-group row">
      <label for="productName" class="col-sm-2 col-form-label">Product Name</label>
      <div class="col-sm-10">
        <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control', placeholder: 'Product Name', required: true %>
      </div>
    </div>
    <div class="form-group row">
      <label for="productPrice" class="col-sm-2 col-form-label">Price</label>
      <div class="col-sm-10">
        <%= f.number_field :price, step: 0.5, autocomplete: "price", class: 'form-control', placeholder: 'Price', required: true %>
      </div>
    </div>
    <div class="form-group row">
      <label for="productPrice" class="col-sm-2 col-form-label">Image</label>
      <div class="col-sm-10">
        <%= f.file_field(:image, accept: 'image/png,image/gif,image/jpeg', class: 'form-control') %>
      </div>
    </div>
    <div class="form-group row">
      <label for="productDescription" class="col-sm-2 col-form-label">Description</label>
      <div class="col-sm-10">
        <%= f.text_area :description, autocomplete: "description", class: 'form-control', placeholder: 'Description' %>
      </div>
    </div>
    <div class="form-group row">
      <label for="lastBiddingDate" class="col-sm-2 col-form-label">Last Date</label>
      <div class="col-sm-10">
        <%= f.date_field :last_bidding_date, autocomplete: "last_bidding_date", class: 'form-control', placeholder: 'Last Date', min: Date.today + 1 %>
      </div>
    </div>
    <div class="form-group row">
      <div class="actions col-sm-6">
        <%= f.submit "Submit", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<span class="ml-auto">
  <%= link_to 'New Product', new_product_path, class: "btn btn-success" %>
</span>
<div class="col-md-12">
  <% if @products.empty? %>
    <div>
      <h2 class="text-danger text-center">No Products Found</h2>
    </div>
  <% else %>
    <section id="team" class="pb-5">
      <div class="container">
        <div class="row">
          <% @products.each do |product|%>
            <!-- Team member -->
            <div class="col-xs-12 col-sm-6 col-md-4">
              <%# <div class="image-flip" ontouchstart="this.classList.toggle('hover');"> %>
              <div class="">
                <div class="mainflip">
                  <div class="frontside">
                    <div class="card">
                      <div class="card-body text-center">
                        <%= link_to product, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-product" do %>
                          <%# <i class="fa fa-times" aria-hidden="true" title="Delete"></i> %>
                          <span title="Delete">X</span>
                        <% end %>
                        <p>
                          <% if product.image.present? %>
                            <%= image_tag product.image.url, class: "avatar-img" %>
                          <% else %>
                            <%= image_tag(image_path('box.png'), class: "avatar-img") %>
                          <% end %>
                        </p>
                        <h4 class="card-title">
                          <%= link_to product.name.humanize, product_path(product.id), class: "standard-link text-info" %>
                          <p class="text-danger">
                            <%= image_tag(image_path('rupee.png'), style: "width: 25px; height: 20px; border-radius: 0;") %>
                            <%= product.price %>
                          </p>
                        </h4>
                        <div class="card-text" style="height: 4rem; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                          <% if product.description.present? %>
                            <%= product.description %>
                          <% else %>
                            This section shows the product desctiption. Currently no description added by the user
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="backside">
                    <div class="card">
                      <div class="card-body text-center mt-4">
                        <h4 class="card-title">Product Description Section</h4>
                        <p class="card-text">
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </section>
  <% end %>
  <%# <div class="mt-5 float-right">
    <%= will_paginate @products, renderer: WillPaginate::ActionView::BootstrapLinkRenderer % >
  </div> %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container" style="margin-top: 5rem;">
  <!--<div class="text-success p-3"><%= notice %></div> -->
  <div class="row">
    <div class="col-md-6 product_img">
      <% if @product.image.present? %>
        <%= image_tag @product.image.url, style: "width: 20rem; height: 20rem; border-radius: 0;" %>
      <% else %>
        <%= image_tag(image_path('gallery.png'), style: "width: 20rem; height: 20rem; border-radius: 0;") %>
        <br />
        No Photos uploaded
      <% end %>
    </div>
    <div class="col-md-6 product_content">
      <div class="text-left bg-light p-3">
        <p class="h4 text-success"><%= @product.name %></p>
        <div class="row text-left">
          <dt class="col-md-4">Description:</dt>
          <dd class="text-left">
            <%=@product.description%>
          </dd>
        </div>
        <div class="row text-left">
          <dt class="col-md-4">Original Price:</dt>
          <dd class="text-left">
            <span class="text-danger">
              <%= image_tag(image_path('rupee.png'), style: "width: 25px; height: 20px; border-radius: 0;") %>
              <%= @product.price %>
            </span>
          </dd>
        </div>
        <div class="row text-left">
          <dt class="col-md-4">Last Bidding Date:</dt>
          <dd class="text-left">
            <%= Date.parse(@product.last_bidding_date.to_s) %>
          </dd>
        </div>
        <hr>
      </div>
      <hr>
      <div class="bg-light p-3" style="min-height: 12rem;">
        <% if @product.last_bidding_date >= Date.today %>
          <h3>Set your bid:</h3>
          <div class="">
            <%= form_for @product.bid, url: update_bid_product_path(@product) do |f| %>
              <div class="form-group row">
                <label for="productPrice" class="col-sm-2 col-form-label">Price:</label>
                <div class="col-sm-7">
                  <%= f.number_field :current_bid, step: 0.5, autocomplete: "price", class: 'form-control', placeholder: 'Price', required: true %>
                </div>
                <div class="form-group col-sm-2">
                  <div class="actions">
                    <%= f.submit "Update", class: "btn btn-success" %>
                  </div>
                </div>
              </div>
            <% end %>
            <% if notice%>
              <% if notice["type"].eql?('error')%>
                <p class="text-danger"><%= notice["message"] %></p>
              <% elsif notice["type"].eql?('success') %>
                <p class="text-success"><%= notice["message"] %></p>
              <% else %>
                <p class="text-info"><%= notice["message"] %></p>
              <% end %>
            <% end %>
          </div>
        <% else %>
          <div class="text-danger">This product is already sold</div>
        <% end %>
      </div>
      <hr>
      <div class="bg-light p-3">
        <h4>Recent Bid Details</h4>
        <hr>
        <div>
          <% if(@product.status.eql?('pending') && @product.price != @product.bid.current_bid) %>
            <div class="row text-left">
              <dt class="col-md-5">New Price:</dt>
              <dd class="text-left">
                <span class="text-danger">
                  <%= image_tag(image_path('rupee.png'), style: "width: 25px; height: 20px; border-radius: 0;") %>
                  <%= @product.bid.current_bid %>
                </span>
              </dd>
            </div>
            <div class="row text-left">
              <dt class="col-md-5">Bid Placed By:</dt>
              <dd class="text-left text-info">
                <p>Name: <%= @bid_user_name %></p>
                <p>Email: <%= @bid_user.email %></p>
                <p>Contact number: <%= @bid_user.profile.mobile || "N/A" %></p>
              </dd>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>