config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: {
    confirmations: 'confirmations'
  }
  get 'welcome/index'

  resources :products do
    member do
      patch :update_bid
    end
  end

  resources :categories

  get '/profiles/rank' => 'profiles#rank'
  get 'profiles/rank_request' => 'profiles#rank_request'
  resources :profiles

  root 'welcome#index'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top" style="background-color: #e3f2fd;">
  <%= link_to root_path, class: 'nav-link navbar-brand' do %>
    <i class="fa fa-snowflake-o"></i> GREAT ESTATE
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%# <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul> %>
  <ul class="navbar-nav ml-auto">
    <% unless signed_in? %>
      <li class="nav-item">
        <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Signup', new_user_registration_path, class: 'nav-link' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to 'Profile', profile_path(current_user.profile.id), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
</div>
</nav>

app/views/layouts/_not_fount.html.erb
<%= stylesheet_link_tag    'my-style', media: 'all' %>
<style type="text/css">
	.notfound .notfound-404 h1 {
		font-family: 'Montserrat', sans-serif;
		font-size: 230px;
		margin: 0px;
		font-weight: 900;
		position: absolute;
		left: 50%;
		-webkit-transform: translateX(-50%);
		-ms-transform: translateX(-50%);
		transform: translateX(-50%);
		background: url("<%= image_path('bg.jpg')%>") no-repeat;
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		background-size: cover;
		background-position: center;
	}
	
</style>
<div id="notfound">
	<div class="notfound">
		<div class="notfound-404">
			<h1>Oops!</h1>
		</div>
		<h2>404 - Page not found</h2>
		<p>The page you are looking for might have been removed had its name changed or is temporarily unavailable.</p>
		<%= link_to 'Go To Dashboard', root_path %>
	</div>
</div>

app/views/layouts/_sidenav.html.erb
<div class="sidenav">
  <%= link_to products_path do %>
    <%= image_tag(image_path('products.png'), class: '', title: 'Products') %>
    <span>Products</span>
  <% end %>
  <% if signed_in? && current_user.admin? %>
    <%= link_to profiles_path do %>
      <%= image_tag(image_path('team.png'), class: '', title: 'Profiles') %>
      <span>Profiles</span>
    <% end %>
    <%= link_to categories_path do %>
      <%= image_tag(image_path('list.png'), class: '', title: 'Categories') %>
      <span>Categories</span>
    <% end %>
  <% end %>
  <a href="#services">
    <%= image_tag(image_path('service.png'), class: '', title: 'Services') %>
    <span>Services</span>
  </a>
  <a href="#clients">
    <%= image_tag(image_path('clients.png'), class: '', title: 'Clients') %>
    <span>Clients</span>
  </a>
  <a href="#contact">
    <%= image_tag(image_path('contact.png'), class: '', title: 'Contact') %>
    <span>Contact</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineAuction</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/sidenav" %>
    <%= render "layouts/navbar" %>
    <div class="main">
      <!--<p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p> -->
      <%= yield %>
    </div>
  </body>
</html>